"""Add updated_at to MenuItem and create InventoryItem and MenuRecipe models

Revision ID: 237192dec6b3
Revises: 
Create Date: 2025-09-06 12:11:42.951186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237192dec6b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
